# Generated by Django 4.0.3 on 2022-04-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExitEntryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskForceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_code', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=8)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HKUMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hkuID', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('Venue', models.ManyToManyField(through='Core.ExitEntryRecord', to='Core.venue')),
            ],
        ),
        migrations.AddField(
            model_name='exitentryrecord',
            name='HKUMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.hkumember'),
        ),
        migrations.AddField(
            model_name='exitentryrecord',
            name='Venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.venue'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('Venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.venue')),
            ],
        ),
    ]
