# Generated by Django 4.0.4 on 2022-05-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExitEntryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=8)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HKUMember',
            fields=[
                ('hkuID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('Venue', models.ManyToManyField(through='Core.ExitEntryRecord', to='Core.venue')),
            ],
        ),
        migrations.AddField(
            model_name='exitentryrecord',
            name='HKUMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.hkumember'),
        ),
        migrations.AddField(
            model_name='exitentryrecord',
            name='Venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.venue'),
        ),
    ]
