# Generated by Django 4.0.3 on 2022-04-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exitentryrecord',
            old_name='hkuID',
            new_name='HKUMember',
        ),
        migrations.RenameField(
            model_name='exitentryrecord',
            old_name='venue_code',
            new_name='Venue',
        ),
    ]
