# Generated by Django 4.0.4 on 2022-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hkumember',
            name='hkuID',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hkumember',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_code',
            field=models.CharField(max_length=20),
        ),
    ]
