# Generated by Django 4.0.3 on 2022-04-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_rename_hkuid_exitentryrecord_hkumember_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='venue',
            new_name='Venue',
        ),
        migrations.RenameField(
            model_name='hkumember',
            old_name='venue_code',
            new_name='Venue',
        ),
    ]
